# From https://hub.docker.com/_/mongo
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

  backend:
    depends_on: 
      - mongo
    build: .
    environment:
      MONGO_URL: mongo
    ports:
      - 3000:3000
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081  